### ISSUE TITLE
Blocks are not properly registered using register_block_type and do not appear in block editor (for built plugin on wordpress.org/plugins)

### ISSUE THREAD

**Issue by skorasaurus** [createwithrani/superlist#40]
Hi, 

I downloaded your plugin from the plugin directory this morning (I used wp-cli but that shouldn't affect it; it still fetches the plugin from https://downloads.wordpress.org/plugin/superlist-block.0.1.0.zip ) and activated it but I received the following notice in my terminal after installation signifying that the block wasn't properly registered. 

I'm not 100% sure, but I think the cause is that [register_block_type](https://github.com/createwithrani/superlist/blob/5d43d6ed8c51249efd1ffe6915dbdf452ad1e42a/superlist-block.php) is expecting a block.json file in the build/superlist directory and such a directory does not exist. 

I'm using Gutenberg 13.4.0; no other plugins installed. WP 6.0.0.

> PHP Notice:  Function WP_Block_Type_Registry::register was called <strong>incorrectly</strong>. Block type names must contain a namespace prefix. Example: my-plugin/my-custom-block-type Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.0.0.) in /path/to/my/wordpress_install/public_html/wp-includes/functions.php on line 5831
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/wp:0
PHP   2. include() /usr/local/bin/wp:4
PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:11
PHP   4. WP_CLI\bootstrap() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php:27
PHP   5. WP_CLI\Bootstrap\LaunchRunner->process($state = class WP_CLI\Bootstrap\BootstrapState { private $state = ['context_manager' => class WP_CLI\ContextManager { private $contexts = ['cli' => class WP_CLI\Context\Cli {  }, 'admin' => class WP_CLI\Context\Admin {  }, 'frontend' => class WP_CLI\Context\Frontend {  }, 'auto' => class WP_CLI\Context\Auto { private $context_manager = ... }]; private $current_context = 'cli' }] }) phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php:78
PHP   6. WP_CLI\Runner->start() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php:28
PHP   7. WP_CLI\Runner->load_wordpress() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1235
PHP   8. require() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1317
PHP   9. do_action($hook_name = 'init') /path/to/my/wordpress_install/public_html/wp-settings.php:598
PHP  10. WP_Hook->do_action($args = [0 => '']) /path/to/my/wordpress_install/public_html/wp-includes/plugin.php:476
PHP  11. WP_Hook->apply_filters($value = '', $args = [0 => '']) /path/to/my/wordpress_install/public_html/wp-includes/class-wp-hook.php:331
PHP  12. create_block_superlist_block_block_init('') /path/to/my/wordpress_install/public_html/wp-includes/class-wp-hook.php:307
PHP  13. register_block_type($block_type = '/path/to/my/wordpress_install/public_html/wp-content/plugins/superlist-block/build/superlist', $args = *uninitialized*) /path/to/my/wordpress_install/public_html/wp-content/plugins/superlist-block/superlist-block.php:29
PHP  14. WP_Block_Type_Registry->register($name = '/path/to/my/wordpress_install/public_html/wp-content/plugins/superlist-block/build/superlist', $args = []) /path/to/my/wordpress_install/public_html/wp-includes/blocks.php:393
PHP  15. _doing_it_wrong($function = 'WP_Block_Type_Registry::register', $message = 'Block type names must contain a namespace prefix. Example: my-plugin/my-custom-block-type', $version = '5.0.0') /path/to/my/wordpress_install/public_html/wp-includes/class-wp-block-type-registry.php:77
PHP  16. trigger_error($message = 'Function WP_Block_Type_Registry::register was called <strong>incorrectly</strong>. Block type names must contain a namespace prefix. Example: my-plugin/my-custom-block-type Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.0.0.)', $error_type = 1024) /path/to/my/wordpress_install/public_html/wp-includes/functions.php:5831
PHP Notice:  Function WP_Block_Type_Registry::register was called <strong>incorrectly</strong>. Block type names must contain a namespace prefix. Example: my-plugin/my-custom-block-type Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.0.0.) in /path/to/my/wordpress_install/public_html/wp-includes/functions.php on line 5831
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/wp:0
PHP   2. include() /usr/local/bin/wp:4
PHP   3. include() phar:///usr/local/bin/wp/php/boot-phar.php:11
PHP   4. WP_CLI\bootstrap() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php:27
PHP   5. WP_CLI\Bootstrap\LaunchRunner->process($state = class WP_CLI\Bootstrap\BootstrapState { private $state = ['context_manager' => class WP_CLI\ContextManager { private $contexts = ['cli' => class WP_CLI\Context\Cli {  }, 'admin' => class WP_CLI\Context\Admin {  }, 'frontend' => class WP_CLI\Context\Frontend {  }, 'auto' => class WP_CLI\Context\Auto { private $context_manager = ... }]; private $current_context = 'cli' }] }) phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php:78
PHP   6. WP_CLI\Runner->start() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php:28
PHP   7. WP_CLI\Runner->load_wordpress() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1235
PHP   8. require() phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1317
PHP   9. do_action($hook_name = 'init') /path/to/my/wordpress_install/public_html/wp-settings.php:598
PHP  10. WP_Hook->do_action($args = [0 => '']) /path/to/my/wordpress_install/public_html/wp-includes/plugin.php:476
PHP  11. WP_Hook->apply_filters($value = '', $args = [0 => '']) /path/to/my/wordpress_install/public_html/wp-includes/class-wp-hook.php:331
PHP  12. create_block_superlist_block_block_init('') /path/to/my/wordpress_install/public_html/wp-includes/class-wp-hook.php:307
PHP  13. register_block_type($block_type = '/path/to/my/wordpress_install/public_html/wp-content/plugins/superlist-block/build/superlist-item', $args = *uninitialized*) /path/to/my/wordpress_install/public_html/wp-content/plugins/superlist-block/superlist-block.php:30
PHP  14. WP_Block_Type_Registry->register($name = '/path/to/my/wordpress_install/public_html/wp-content/plugins/superlist-block/build/superlist-item', $args = []) /path/to/my/wordpress_install/public_html/wp-includes/blocks.php:393
PHP  15. _doing_it_wrong($function = 'WP_Block_Type_Registry::register', $message = 'Block type names must contain a namespace prefix. Example: my-plugin/my-custom-block-type', $version = '5.0.0') /path/to/my/wordpress_install/public_html/wp-includes/class-wp-block-type-registry.php:77
PHP  16. trigger_error($message = 'Function WP_Block_Type_Registry::register was called <strong>incorrectly</strong>. Block type names must contain a namespace prefix. Example: my-plugin/my-custom-block-type Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.0.0.)', $error_type = 1024) /path/to/my/wordpress_install/public_html/wp-includes/functions.php:5831

**Comment by skorasaurus** [comment]
I can confirm this is only an issue with the current version uploaded into the wordpress.org plugin registry.

I cloned the repo and then built it locally and the block works as expected. :)

**Comment by pdemaria** [comment]
Hi! Great plugin... As stated previously, yes if you  `npm run build` on this repo code... the plugin works fine.

So `./build`... on the version of the plugin that's in the plugin directory... the directory looks like this:
- images/
- style-superlist-item.css
- style-superlist-item.css.map
- style-superlist.css
- style-superlist.css.map
- superlist-item.asset.php 
- superlist-item.css
- superlist-item.css.map
- superlist-item.js
- superlist-item.js.map
- superlist.asset.php
- superlist.css
- superlist.css.map
- superlist.js
- superlist.js.map

If I change the register_block_type path from `build/` to `src/` that Wordpress.org plugin works... (and I can see in the `block.json` it's actually referencing assets in the build directory FROM `block.json` in `./src`)

I'd love to contribute but I'm not sure how this works... between what's on WP SVN  and what's on the repo? Whatever that bit is that packages things for SVN is not running properly

**Comment by pdemaria** [comment]
So maybe something like this is munging things...  uses: actions/upload-release-asset@v1  (which is archived)

Maybe should use https://github.com/softprops/action-gh-release ?

**Comment by aurooba** [comment]
Hey folks! Thanks for this. I'm looking into fixing and adjusting this plugin in the next couple days. I know it has become non-functional while my attention was on other things. Expect an update in the next couple days!

**Comment by zu** [comment]
Thanks @aurooba. It seems, that would also solve the problems mentioned on wp.org: https://wordpress.org/support/topic/block-installs-and-activates-but-wont-show-up/

**Comment by aurooba** [comment]
Thanks for your patience everyone! WordPress.org version has been fixed!
